#' Correct for turbine clustering
#' 
#' The construction of the CRM requires that the flight flux through the observed 
#' window be scaled to the size of a turbine and then applied to each turbine. If 
#' If the (effective) detection range of the observer overlaps multiple turbines
#' the flux needs to be scaled appropriate over the turbines in the observation
#' range.
#' 
#' @details
#' If the turbine layout is more compact and/or your effective detection width is large, then the effective detection area contains more than one turbine, in which case the observed flux needs to be weighted to account for the effective turbines in the observed area. This accounts for the fact that the observed flux is an instantaneous measure and cannot interact with multiple turbines at once.
#' 
#' This package provides a 1D line correction [cluster_correction_l()] and 2D aerial [cluster_correction_a()].
#' 
#' ##  [cluster_correction_l()]
#' 
#' The 1D (line) correction calculates the ratio of the effective strip width (ESW) and the mean distance between each turbine and it's nearest neighbour. It's suitable for line transects or for interim CRM early in the project life-cycle where the turbine spacing can be estimated but the layout may not be available.
#' 
#' ## [cluster_correction_a()]
#' 
#' The 2D aerial correction places a buffer of radius equal to the effective detection radius (EDR) around each turbine, then generates a spatial union of those buffers. The correction is the ratio of the actual turbine area to the area if the turbine buffers do not overlap.
#'  
#' ## Relationship to other spatial corrections
#' 
#' This correction is derived from different assumptions but fulfils a similar model correction as the \code{sqrt(n_turbines)} in previous CRM  \insertCite{Smales2013,Band2012}{collision}. 
#' 
#' Alternatively, a spatial probability surface can be generated by the analyst using kernel density estimate (KDE) or similar and used instead to estimate the proportion of flights at a given turbine estimation.  That approach requires more data and site coverage.
#' 
#'
#' 
#'    
#'    
#' @name cluster_correction    



#' @rdname cluster_correction
#'
#' @param eff_detection_width numeric; the total effective detection width which is 
#'     2 x effective detection radius or 2 x effective strip (half) width. 
#' @param df_turbines data.frame; a data.frame with one row per turbine, 
#'    containing the coordinates of each turbine as latitude, longitude pairs. 
#'    Coordinate columns can be named (lon, long, longitude, x) and (lat, latitude, y)
#' @param crs optional coordinate system epsg code for the coordinates.  Defaults to crs = 4326 (WGS 84 - lat/lon). 
#' 
#' 
#' @return numeric; the minimum of 1 or a fractional scaling factor, calculated as the ratio of the total area covered by the turbines buffered by the EDA divided by the area if each turbine buffer were completely independent.
#' 
#' @examples
#' 
#' # generate inputs information
#' 
#' df_turbines <- data.frame(
#'   turbine_id = c("T1", "T2", "T3"),
#'   lat = c(-35.036287, -35.03900, -35.03200),
#'   lon = c(145.947140, 145.94500, 145.94200)
#' )
#' 
#' eff_detection_width <- 500 
#' 
#' cluster_correction_a(eff_detection_width = 500, df_turbines, crs = 4326)
#' 
#' @export
cluster_correction_a <- function(eff_detection_width, df_turbines, crs = 4326){
  
  stopifnot('eff_detection_width must be a single numeric value' = 
              length(eff_detection_width) == 1)
  check_num_bounds(eff_detection_width, min = 1, max = Inf)
  
  
  sf_turbines <- df_to_projsf(df_turbines, crs) # internal helper function
  
  ## total area with no overlap
  area_separate <- nrow(df_turbines)* pi*(eff_detection_width*0.5)^2  #half width==radius
  
  ## area buffered by EDA
  sf_turb_buffer <- sf::st_make_valid(
    sf::st_buffer(x = sf_turbines,
                  dist = eff_detection_width*0.5,
                  nQuadSegs = 360))
  
  ## union
  sf_turb_union <- sf::st_make_valid(sf::st_union(sf_turb_buffer))
  
  ## Area
  turb_area_buf <- sf::st_area(sf_turb_union) |> as.numeric()
  
  ## return
  turbine_prob <- min( turb_area_buf/area_separate, 1.0 ) 
  
  return(turbine_prob)
}


#' @rdname cluster_correction
#'
#' @param avg_min_distance numeric; (optional) the mean distance between each turbine and its nearest neighbour. Alternatively you can input a data.frame with turbine coordinates
#' @param eff_detection_width numeric; the effective detection (half) width or effective detection radius
#' @param df_turbines data.frame; (optional) a data.frame with one row per turbine, 
#'    containing the coordinates of each turbine as latitude, longitude pairs. 
#'    Coordinate columns can be named (lon, long, longitude, x) and (lat, latitude, y)
#' @param crs optional coordinate system epsg code for the coordinates.  Only used if df_turbines provided. Defaults to crs = 4326 (WGS 84 - lat/lon). 
#'
#'
#' @return numeric; the minimum of 1 or a fractional scaling factor, calculated as the ratio of the average distance between turbine neighbours and the effective strip width
#' 
#' @examples
#' 
#' # generate input data
#' 
#' 
#' df_turbines <- data.frame(
#'   turbine_id = c("T1", "T2", "T3"),
#'   lat = c(-35.036287, -35.03900, -35.03200),
#'   lon = c(145.947140, 145.94500, 145.94200)
#' )
#'
#' ##option 1 - provide the average distance between turbine neighbours
#' 
#' sf_turbines <- sf::st_as_sf(df_turbines, 
#'   coords = c(lon_col, lat_col), 
#'   crs = 4326)
#'   
#' idx <- sf::st_nearest_feature(sf_turbines)
#' dist_avg <- sf::st_distance(sf_turbines, sf_turbines[idx,], by_element=TRUE) |>
#'    mean() |>
#'    as.numeric()
#' 
#' 
#' corr1 <- cluster_correction_l(eff_detection_width = 800, 
#'                               avg_min_distance = dist_avg)
#'    
#' ## option 2 - provide the data frame (might be slower)
#'  
#' corr2 <- cluster_correction_l(eff_detection_width = 800, 
#'                               df_turbines = df_turbines,
#'                               crs = 4326 # provide crs with turbines
#'                               )
#'  ## should be equal (or very very close)
#'  corr1; corr2
#' 
#' @export
cluster_correction_l <- function(eff_detection_width,
                                 avg_min_distance = NULL,
                                 df_turbines = NULL,
                                 crs = 4326){

  stopifnot('eff_detection_width must be a single numeric value' = 
              length(eff_detection_width) == 1)


  check_num_bounds(eff_detection_width, min = 1, max = Inf)
  
  
  if( is.null(avg_min_distance ) & is.null(df_turbines)){
    stop("Please enter one of eff_detection_width or avg_min_distance")
  }
    
  if( !is.null(avg_min_distance) & !is.null(df_turbines)){
    stop("Please enter only one of eff_detection_width and avg_min_distance")
  }
    
  
  if(!is.null(avg_min_distance)){
    stopifnot('avg_min_distance must be a single numeric value' = 
                length(avg_min_distance) == 1)
    check_num_bounds(avg_min_distance, min = 1, max = Inf)
  }
  
  if(!is.null(df_turbines)){
    
    sf_turbines <- df_to_projsf(df_turbines, crs) # internal helper function
    
    #index of nearest neighbour
    idx <- sf::st_nearest_feature(sf_turbines)
    
    #calculate average distance
    avg_min_distance <- sf::st_distance(sf_turbines, 
                                        sf_turbines[idx,], 
                                        by_element=TRUE) |>
      mean() |>
      as.numeric()
  }
  
    
  return(min(avg_min_distance/eff_detection_width, 1.0)) 
}


# Convert df to sf
# 
# helper function shared by the cluster correction functions
# 
# @returns sf object in projected coords
df_to_projsf <- function(df_turbines, crs){
  
  ## checks
  stopifnot(
    "df_turbines must be a data.frame" =
      is.data.frame(df_turbines)
  )
  stopifnot(
    "df_turbines must have at least one row" =
      nrow(df_turbines) >= 1
  )
  
  ## Grab coordinate data and check
  lon_col <- names(df_turbines)[
    tolower(names(df_turbines)) %in% c("lon",
                                       "longitude",
                                       "long",
                                       "x",
                                       "easting")
  ]
  
  lat_col <- names(df_turbines)[
    tolower(names(df_turbines)) %in% c("lat",
                                       "latitude",
                                       "y",
                                       "northing")
  ]
  
  stopifnot(
    "df_turbines must contain one longitude column named lon, long, longitude, x, or easting" =
      length(lon_col) == 1
  )
  stopifnot(
    "df_turbines must contain one latitude column named lat, latitude, y, or northing" =
      length(lat_col) == 1
  )
  
  sf_turbines <- sf::st_as_sf(df_turbines, 
                              coords = c(lon_col, lat_col), 
                              crs = crs)

  
  # Convert to projected coord system for calc in metres
  if(sf::st_is_longlat(sf_turbines)){
    
    check_num_bounds(sf::st_coordinates(sf_turbines)[, "X"], -180, 180 )
    check_num_bounds(sf::st_coordinates(sf_turbines)[, "Y"], -90, 90 )
    
    projcrs <- lonlat_to_utm(sf::st_coordinates(sf_turbines))
    sf_turbines <- sf::st_transform(sf_turbines, crs = projcrs)
    
  }
    
  check_num_bounds(sf::st_coordinates(sf_turbines)[, "X"], 150000, 1e6 )
  check_num_bounds(abs(sf::st_coordinates(sf_turbines)[, "Y"]), 1.e6, 10.e6  )
  
  
  return(sf_turbines)
  
}